# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5688624e82ef5b52a62e269c370ef0b59844b7d05ece52e3afb770ec6e171e3c717fa25db1ae33cb32a17e7076bae820cdc1982dbbec7612d228a5a4ec4c8c6

test:
  secret_key_base: cd0baebe6c22dbf80adc84319641e8544d85281e39fa43343d6abd469ea84b1e6e3b962ca227faa4dcdaed74851897a4b675976388e21b85e87c9e6e216d109a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
